version: 2
updates:
  - package-ecosystem: "pip"
    # root directory
    directory: "/"
    schedule:
      interval: "weekly"
    # one pull request
    groups:
      pip-dependencies:
        patterns:
          - "*"
