import { defineConfig, type PluginOption } from "vite";
import { readFileSync, mkdirSync, writeFileSync, existsSync } from "fs";
import { dirname, resolve } from "path";

/**
 * Build strategy:
 *
 * All front-end JavaScript has been migrated to ES modules under
 * front/web/src/. Vite bundles them into a single IIFE
 * (miminet.entry.js) that Flask serves from static/dist/.
 *
 * The CLASSIC_BUNDLE list is kept (currently empty) so that future
 * fall-back files — e.g. a vendor script that can't be importable —
 * can be re-introduced without re-architecting the build.
 */

const STATIC_ROOT = resolve(__dirname, "../src/static");
const DIST_ROOT = resolve(STATIC_ROOT, "dist");

const CLASSIC_BUNDLE: string[] = [];

const concatClassicScripts = (): PluginOption => ({
    name: "miminet-concat-classic-scripts",
    apply: "build",
    closeBundle() {
        if (CLASSIC_BUNDLE.length === 0) {
            return;
        }
        const banner =
            "/* miminet classic-script bundle\n" +
            " * Generated by front/web/vite.config.ts — do not edit by hand.\n" +
            " * Source files live under front/src/static/{netfront,config_forms}/.\n" +
            " */\n\n";
        const parts: string[] = [banner];
        for (const rel of CLASSIC_BUNDLE) {
            const abs = resolve(STATIC_ROOT, rel);
            if (!existsSync(abs)) {
                throw new Error(`Bundle source missing: ${abs}`);
            }
            parts.push(`/* --- ${rel} --- */\n${readFileSync(abs, "utf8")}\n`);
        }
        const outFile = resolve(DIST_ROOT, "miminet.classic.js");
        mkdirSync(dirname(outFile), { recursive: true });
        writeFileSync(outFile, parts.join("\n"));
    },
});

export default defineConfig({
    build: {
        outDir: DIST_ROOT,
        emptyOutDir: true,
        rollupOptions: {
            input: resolve(__dirname, "src/main.ts"),
            output: {
                entryFileNames: "miminet.entry.js",
                format: "iife",
                name: "MiminetEntry",
            },
        },
    },
    plugins: [concatClassicScripts()],
});
