import { defineConfig, type PluginOption } from 'vite';
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';

/**
 * Phase 2 strategy:
 *
 * The 13 split files under static/netfront/ and static/config_forms/ are
 * currently classic scripts that share global scope. A real ES-module
 * migration (read-only imports + cross-module mutable state) is Phase 3.
 *
 * For Phase 2 we bundle them via plain concatenation so Flask only has to
 * serve one file, and we set up the Vite/TS pipeline that future migrations
 * will compile against.
 */

const STATIC_ROOT = resolve(__dirname, '../src/static');
const DIST_ROOT = resolve(STATIC_ROOT, 'dist');

const CLASSIC_BUNDLE = [
  'netfront/state.js',
  'netfront/show_config.js',
  'netfront/network_ops.js',
  'netfront/draw.js',
  'netfront/simulation.js',
  'netfront/update_config.js',
  'netfront/runtime.js',
  'config_forms/common.js',
  'config_forms/device.js',
  'config_forms/shared.js',
  'config_forms/helpers.js',
  'config_forms/jobs.js',
  'config_forms/edit_jobs.js',
];

const concatClassicScripts = (): PluginOption => ({
  name: 'miminet-concat-classic-scripts',
  apply: 'build',
  closeBundle() {
    const banner =
      '/* miminet classic-script bundle\n' +
      ' * Generated by front/web/vite.config.ts — do not edit by hand.\n' +
      ' * Source files live under front/src/static/{netfront,config_forms}/.\n' +
      ' */\n\n';
    const parts: string[] = [banner];
    for (const rel of CLASSIC_BUNDLE) {
      const abs = resolve(STATIC_ROOT, rel);
      if (!existsSync(abs)) {
        throw new Error(`Bundle source missing: ${abs}`);
      }
      parts.push(`/* --- ${rel} --- */\n${readFileSync(abs, 'utf8')}\n`);
    }
    const outFile = resolve(DIST_ROOT, 'miminet.classic.js');
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile, parts.join('\n'));
  },
});

export default defineConfig({
  build: {
    outDir: DIST_ROOT,
    emptyOutDir: true,
    rollupOptions: {
      input: resolve(__dirname, 'src/main.ts'),
      output: {
        entryFileNames: 'miminet.entry.js',
        format: 'iife',
        name: 'MiminetEntry',
      },
    },
  },
  plugins: [concatClassicScripts()],
});
