version: "3.9"

services:
  miminet:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: celery
    restart: always
    environment:
      - exchange_name=${exchange_name}
      - celery_concurrency=${celery_concurrency}
      - queue_names=${queue_names}
    privileged: true
    networks:
      - redis-network
      - rabbitmq-network
    
networks:
  redis-network:
    name: redis-network
    external: true
  rabbitmq-network:
    name: rabbitmq-network
    external: true
