// Drag-and-drop wiring: device palette icons (.drag) get dropped onto
// the cytoscape canvas (#network_scheme) to create new nodes.
//
// Migrated from front/src/static/netfront.js. The original ran at the
// bottom of the page, after both the palette and the canvas were
// rendered. Bundled now, we run inside $(document).ready so the
// selectors still match.

import {
    SetNetworkPlayerState,
    SaveNetworkObject,
    CalculateDropOffset,
    TakeGraphPictureAndUpdate,
} from "./runtime";
import { HostUid, RouterUid, ServerUid } from "./state";
import { l1HubUid, l2SwitchUid } from "./show_config";
import { PostNodes } from "./network_ops";
import { DrawGraph } from "./draw";
import { PacketPlayer } from "./packet_player";

export function initNetfrontDragDrop() {
    ($(".drag") as any).draggable({
        appendTo: "body",
        helper: "clone",
    });

    ($("#network_scheme") as any).droppable({
        activeClass: "active",
        hoverClass: "hover",
        accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
        drop: function (_e: any, ui: any) {
            const type = ui.draggable.prop("id");

            // Don't drop if network is animated
            if (PacketPlayer.getInstance().getPlayerPlay()) {
                return;
            }

            // We add new device. Drop the network state.
            SetNetworkPlayerState(-1);

            // Save the network state if we gonna CTRL+Z.
            SaveNetworkObject();

            const pos = CalculateDropOffset(ui.position.left, ui.position.top);

            if (type === "host") {
                const node_id = HostUid();
                nodes.push({
                    data: { id: node_id, label: node_id },
                    position: { x: pos.x, y: pos.y },
                    classes: ["host"],
                    config: {
                        type: "host",
                        label: node_id,
                    },
                    interface: [],
                });
            } else if (type === "l2_switch") {
                const node_id = l2SwitchUid();
                nodes.push({
                    data: { id: node_id, label: node_id },
                    position: { x: pos.x, y: pos.y },
                    classes: ["l2_switch"],
                    config: {
                        type: "l2_switch",
                        label: node_id,
                        stp: 0,
                    },
                    interface: [],
                });
            } else if (type === "l1_hub") {
                const node_id = l1HubUid();
                nodes.push({
                    data: { id: node_id, label: node_id },
                    position: { x: pos.x, y: pos.y },
                    classes: ["l1_hub"],
                    config: {
                        type: "l1_hub",
                        label: node_id,
                    },
                    interface: [],
                });
            } else if (type === "l3_router") {
                const node_id = RouterUid();
                nodes.push({
                    data: { id: node_id, label: node_id },
                    position: { x: pos.x, y: pos.y },
                    classes: ["l3_router"],
                    config: {
                        type: "router",
                        label: node_id,
                    },
                    interface: [],
                });
            } else if (type === "server") {
                const node_id = ServerUid();
                nodes.push({
                    data: { id: node_id, label: node_id },
                    position: { x: pos.x, y: pos.y },
                    classes: ["server"],
                    config: {
                        type: "server",
                        label: node_id,
                    },
                    interface: [],
                });
            } else {
                return;
            }

            // post new nodes to the server
            PostNodes();
            DrawGraph();
            TakeGraphPictureAndUpdate();
            return;
        },
    });
}

// Run on DOM ready so the palette + canvas exist before binding.
$(function () {
    if (!document.getElementById("network_scheme")) {
        // Not on a network page — skip.
        return;
    }
    initNetfrontDragDrop();
});
