version: "3.9"

services:
  miminet:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: miminet
    restart: always
    expose:
      - 80
    volumes:
      - databases:/app/instance
      - ./static/images:/app/static/images
      - ./static:/svg:/app/static/svg
      - ./static/video:/app/static/video
      - ./static/pcaps:/app/static/pcaps
    networks:
      - miminet_network
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    networks:
      - miminet_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
           
volumes:
  databases:
  
networks:
  miminet_network:
    driver: bridge
