name: Pytest

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: back/requirements.txt
            
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pytest
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends mininet
          mkdir -p /opt/mininet_dependencies
          pip install -r back/requirements.txt
          
      - name: Test with pytest
        run: |
          cd back/src
          sudo python -m pytest .
          
